# Generated by Django 5.0.4 on 2024-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Review', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Review', max_length=50),
        ),
    ]
